---
- name: Apache server installed
  hosts: web

  tasks:
  - name: Apache enabled and running
    service:
      name: httpd
      enabled: false

  - name: latest Apache version installed
    yum:
      name: httpd
      state: absent

  - name: latest firewalld version installed
    yum:
      name: firewalld
      state: latest

  - name: firewalld enabled and running
    service:
      name: firewalld
      enabled: true
      state: started

  - name: firewalld permits http service
    firewalld:
      service: http
      permanent: true
      state: disabled
      immediate: yes
      state: stopped
